sudo: false
dist: trusty
language: node_js
node_js:
- '9'
install:
- npm install
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
script: 
- npm run docs
# cache node_modules to speed up build
cache:
  directories:
    - node_modules
