sass:
    sass_dir: assets/css

markdown: kramdown

kramdown:
    input: GFM
    syntax_highlighter: rouge

keep_files:
    - docs
    - examples
    - next
    - build

exclude:
    - .DS_Store
    - Gemfile.lock
    - node_modules
    - scripts
    - doc-gen
    - generate_docs
    - docs/test
