sass:
    sass_dir: assets/css

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .DS_Store
  - Gemfile.lock
  - node_modules
  - images/original
  - images/scripts
  - doc-gen
